### PR TITLE
fixed an outdated class name on serious-eats-extract-directions

### LINKED ISSUE #42: fix for missing directions from seriouseats
I just installed `org-chef` and tried to insert at point the first recipe I found, which is [this one](https://www.seriouseats.com/recipes/2020/02/pressure-cooker-ribollita.html). Results in an empty directions section.

### PR DESCRIPTION
**Pull request by bdarcus**
This fixes #42. 

I just replaced the old class name with the new one; not sure if you need to account for both?

### CODE REVIEW

**Comment by Chobbes** [comment]
Thanks a bunch :).

**Comment by bdarcus** [comment]
I think I may have missed something; perhaps not just understanding the lisp code exactly or something. 

But the direction element still isn't getting picked up. Here's the HTML code in question:

```html
<div class="recipe-procedures show-large-images">...</div>
```

**Comment by bdarcus** [comment]
The problem is the regex is too strict, and assumes a single class on the element. While it will work with simply removing the `$` at the end, I think it would be better to remove both of the wildcards?

**Comment by bdarcus** [comment]
Also, here's the results. Do you have a way to clean up the whitespace and such?

image

**Pull request merged**
