### PR TITLE
Support fetching recipes from finecooking.com

### PR DESCRIPTION
**Pull request by egh**
That's it. Works for me. Thanks for the package!

### CODE REVIEW

**Comment by Chobbes** [comment]
Looks good, thanks!

Would you mind including the original copyright with yours amended? Thanks again!

**Comment by egh** [comment]
Oops! Of course, sorry!

**Comment by Chobbes** [comment]
No problem, just want to make sure. Depending on what file you modified there might be somebody besides me :).

**Comment by egh** [comment]
@Chobbes Fixed in 4cc9145

**Comment by Chobbes** [comment]
Merci!

**Pull request merged**
